Module6 task1
htmlacademy-php1/442219-readme-13 pull request #10
Opened 2021-08-23 10:54 UTC by IgorViV

2021-08-24 18:25 UTC, ademaro commented
Можем привести кодовую базу в порядок немного: из корня проекта убрать все шаблоны (*html) в какую-нибудь папку, например, layout/

2021-08-24 18:32 UTC, ademaro commented on templates/main.php
> +                        <a class="filters__button filters__button--ellipse filters__button--all <?php if (!$type_id) print('filters__button--active'); ?>" href="index.php?id=0">
Тут не тернарный, тк смущает пустой else?)
```php
<?= (!$type_id) ? 'filters__button--active') : ''; ?>
```
Можно и так, как вариант:
```php
<?php if (!$type_id) : ?>filters__button--active<?php endif; ?>
```
Выше тож правильно, если что))

2021-08-24 18:33 UTC, ademaro commented on templates/main.php
> +                    <?php foreach($types as $type): ?>
после foreach — пробел давай поставим

2021-08-24 18:35 UTC, ademaro commented on templates/main.php
> +                            <a class="filters__button filters__button--photo button <?php if ($type_id == $type['id']) print('filters__button--active'); ?>" href="index.php?id=<?= $type['id']; ?>">
используем только строгое сравнение (есть формальный критерий для защты проекта, рекомендую все прочитать, что не совсем понятно будет — обсудим)

2021-08-24 18:36 UTC, ademaro commented on templates/main.php
> +                                    <use xlink:href="#icon-filter-<?= $type['class'] ?>"></use>
class — как-то не очень подходит, с именованиями надо поработать чуть более внимательно, от этого зависит дальнейшая разработка и поддержка кода

2021-08-24 18:37 UTC, ademaro commented on templates/main.php
> +                                    <use xlink:href="#icon-filter-<?= $type['class'] ?>"></use>
например, `alias` или `name` или `code` какой-нибудь подошло бы лучше, классы в разных контекстах означают разное, нам это будет только мешать

2021-08-24 18:39 UTC, ademaro commented on templates/main.php
>              <?php foreach($posts as $key => $value): ?>
во всех форычах для $key и $value придумываем адекватные названия (про пробел тож не пишу больше)

2021-08-24 18:52 UTC, ademaro commented on templates/post-popular.php
>          <?php if($value['class'] == 'quote'): ?>
хм, у нас же есть шаблоны для каждого типа поста, зачем дублируем, как-то не по DRY...

2021-08-24 18:54 UTC, ademaro commented on templates/post-popular.php
>          <?php if($value['class'] == 'quote'): ?>
arr_content — надо переименовать (вообще можно над функцией поработать чуть больше, что бы избавиться от этих «странных» индексов)

2021-08-24 18:54 UTC, ademaro commented on templates/post-popular.php
>          <?php if($value['class'] == 'quote'): ?>
по отступам заодно подправить бы сразу

2021-08-24 18:57 UTC, ademaro commented on functions.php
> +
вложенность условий большая получилась. Вообще рекомендую чутка переписать функцию заодно и упростить где можно

2021-08-24 18:58 UTC, ademaro commented on index.php
>      if (!$link) {
подключение к БД и проверку линка — в отдельный файл предлагаю, что бы не дублировать в каждом контроллере

2021-08-24 19:00 UTC, ademaro commented on index.php
> +    $sql_posts = 'SELECT COUNT(likes.id) likes, posts.id AS post_id, posts.title, posts.text_content, posts.img_url, posts.video_url, posts.site_url, user_name AS author, types.class, users.avatar_ur
давай вынесем сами запросы в отдельный файл (например, models.php) и оформим в виде удобных функций, например, get_content_types() и get_posts(),...

2021-08-24 19:03 UTC, ademaro requested changes
Пока оставляю открытым ПР, жду на консультацию, разберём всё более подробно и детально, пока продолжаем рефакторить) В целом — всё хорошо, работать можем и много чего в правильном направлении!

2021-08-26 22:43 UTC, IgorViV commented on templates/post-popular.php
>          <?php if($value['class'] == 'quote'): ?>
> хм, у нас же есть шаблоны для каждого типа поста, зачем дублируем, как-то не по DRY...

Так в шаблонах верстка с дополнительной оберткой на div.

2021-08-31 15:03 UTC, ademaro approved these changes
Пока отлично! Поправки жду в следующем задании отдельным коммитом.

2021-08-31 15:03 UTC, ademaro commented on functions.php
> +                    if (is_double($value)) {
вложенность надо будет поправить

2021-08-31 15:03 UTC, ademaro commented on models.php
> +}
функции в моделях должны возвращать не строки, а уже сами данные из БД.

2021-08-31 15:03 UTC, ademaro commented on post.php
> +$subscribers = db_execute_stmt_assoc($link, $sql_subscribers, [$post['id_user']]);
вот это всё в функции, что бы получилось что-то подобное:
```php
$post = get_post($post_id);
$subscribers = get_subscribers($post_id);
```

2021-08-31 15:03 UTC, ademaro commented on templates/main.php
> +                <?= include_template('post-popular.php', ['index' => $index, 'post' => $post]); ?>
зачем передаём index в шаблон?

2021-08-31 15:03 UTC, merged

2021-08-31 22:53 UTC, IgorViV commented on templates/main.php
> +                <?= include_template('post-popular.php', ['index' => $index, 'post' => $post]); ?>
Это временно для генерации случайной даты публикации с учетом ID поста