Выполняет чтение и показ записей из MySQL
htmlacademy-php1/442219-readme-13 pull request #9
Opened 2021-08-15 20:37 UTC by IgorViV

2021-08-16 00:32 UTC, dshemin requested changes

2021-08-16 00:32 UTC, dshemin commented on data.php
> +    // $posts = [
Если что-то не нужно. То это смело можно удалить. В истории гита это сохранится и можно будет в любой момент достать из него.

2021-08-16 00:32 UTC, dshemin commented on index.php
> +    };
Ненужная `;`.

2021-08-16 00:32 UTC, dshemin commented on index.php
> +    if (!$link) {
Лучше обработать это сразу после соединения, а не потом. Это более лучший подход. Упрощает код и облегчает чтение.

2021-08-16 00:32 UTC, dshemin commented on index.php
> +    require_once('init.php');
Будет лучше назвать файл `config.php`. Это более распространённое именования для файлов, содержащих настройки для приложения.

2021-08-16 00:32 UTC, dshemin commented on templates/post.php
> +                    <!-- <img src="img/coast-medium.jpg" alt="Превью к видео" width="360" height="188"> -->
Почему данный элемент закомментирован?

2021-08-16 06:01 UTC, IgorViV commented on templates/post.php
> +                    <!-- <img src="img/coast-medium.jpg" alt="Превью к видео" width="360" height="188"> -->
После вставки ссылки на youtube поехала верстка первого поста, картинка превью с youtube и поста стали в ряд. Закомментировал временно, разберусь и поправлю.

2021-08-16 08:11 UTC, dshemin commented on templates/post.php
> +                    <!-- <img src="img/coast-medium.jpg" alt="Превью к видео" width="360" height="188"> -->
Думаю можно смело вообще убрать эту картинку. Она была плейсхолдером.

2021-08-18 02:40 UTC, dshemin requested changes

2021-08-18 02:40 UTC, dshemin commented on index.php
> +        $page_content = include_template('error.php', ['error' => $error]);
Тут можно сразу вывести результат на экран и закончить скрипт, чтобы избавится от `else`.

2021-08-18 02:40 UTC, dshemin commented on index.php
> +            $page_content = get_error_template($link);
Тут можно сразу вывести результат на экран и закончить скрипт, чтобы избавится от `else`.

2021-08-18 02:40 UTC, dshemin commented on index.php
> +            $page_content = get_error_template($link);
Тут можно сразу вывести результат на экран и закончить скрипт, чтобы избавится от `else`. Тем более что эта ошибка перетрёт предыдущию.

2021-08-18 02:40 UTC, dshemin commented on index.php
> +        if ($types && $posts) {
Если завершать работу скрипта сразу в тех местах, где произошла ошибка, то можно избежать таких дополнительных проверок.

2021-08-18 03:28 UTC, IgorViV commented on index.php
> +            $page_content = get_error_template($link);
Не совсем понял:

2021-08-18 03:32 UTC, IgorViV commented on index.php
> +            $page_content = get_error_template($link);
Возможно я забыл поставить else на 23 стоке, просто если $types будет с ошибкой, а $posts без неё, то ошибка затрется, поэтому проверки поставил после каждого получения массива и сразу вывод на экран $page_content. Не совсем понял...

2021-08-18 14:22 UTC, dshemin requested changes

2021-08-18 14:22 UTC, dshemin commented on index.php
> +        if ($types) {
Нет, не то. Согласитесь, читать стало в разы сложнее такую лесенку. Попробуйте сделать вот так:
```
$types = get_arr_from_mysql($link, $sql_types);
if (!$types) {
     $page_content = get_error_template($link);

     $layout_content = include_template('layout.php', [
        'is_auth' => $is_auth,
        'user_name' => $user_name,
        'content' => $page_content,
        'title' => 'readme: популярное',
    ]);
    exit;
}

$posts = get_arr_from_mysql($link, $sql_posts);
if (!$posts) {
     $page_content = get_error_template($link);

     $layout_content = include_template('layout.php', [
        'is_auth' => $is_auth,
        'user_name' => $user_name,
        'content' => $page_content,
        'title' => 'readme: популярное',
    ]);
    exit;
}
```

Т.е. мы пытаемся что-то сделать, если не получилось сразу обрабатываем ошибку и завершаем работу. А не накапливаем большой снежный ком, по которому потом будет сложно понять, а собственно когда произошла ошибка.

Естественно у нас есть повторяющийся код, который мы можем обернуть в функцию.

2021-08-18 16:25 UTC, IgorViV commented on index.php
> +        if ($types) {
Спасибо, про exit не знал...

2021-08-19 08:12 UTC, dshemin requested changes

2021-08-19 08:12 UTC, dshemin commented on index.php
> +            $array_layout_data['content'] = get_error_template($link);
Будет лучше сделать функцию `show_error` принемающую только один аргумент - content и завершающую работу скрипта сразу.

2021-08-19 08:12 UTC, dshemin commented on index.php
> +        $page_content = include_template('error.php', ['error' => $error]);
Обратите внимание на этот комментарий. Тут надо сделать тоже самое, вывести ошибку и завершить работу.

2021-08-19 14:25 UTC, dshemin requested changes

2021-08-19 14:25 UTC, dshemin commented on index.php
> +        get_error_template($link);
`get_error_template` возвращает значение, которое тут игнорируется. Точно надо этот метод тут вызывать?

2021-08-19 14:25 UTC, dshemin commented on index.php
> +    } else {
`else` можно убрать, `show_error` завершит работу скрипта.

2021-08-19 14:25 UTC, dshemin commented on index.php
> +            $array_layout_data['content'] = get_error_template($link);
Обратите внимание на этот комментарий.

2021-08-19 14:41 UTC, IgorViV commented on index.php
> +        get_error_template($link);
Думаю да, я его немного модифицировал

2021-08-19 14:43 UTC, dshemin commented on index.php
> +        get_error_template($link);
Но мы тут не используем возвращаемое значение, зачем тогда вызываем?

2021-08-20 15:44 UTC, merged